Repository selsa-inube/inubekit-nav, pull requests merged in 2024-04, with the labels that each got.

#6 Adjust and export interfaces
  src/Nav/index.tsx
  src/index.ts
  vite.config.ts
Labels: minor

#8 Add auto publish
  .autorc.json
  .github/workflows/auto-release.yml
  .gitignore
  package-lock.json
  package.json
  src/NavLink/index.tsx
  src/NavLink/stories/NavLink.stories.tsx
Labels: enhancement

#7 refactor component to use new token structure
  package.json
  src/Nav/index.tsx
  src/Nav/props.ts
  src/Nav/stories/Nav.WithoutSections.stories.tsx
  src/Nav/styles.js
  src/NavLink/index.tsx
  src/NavLink/styles.js
  src/index.ts
Labels: major

#9 Update workflow in order to avoid merges with failed builds
  .github/workflows/auto-release.yml
Labels: minor
