Repository selsa-inube/inubekit-nav, pull requests merged in 2024-10, with the labels that each got.

#56 Update foundations dependency to latest version
  package.json
Labels: minor, dependencies

#57 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#58 Refactor `<NavLink/>` component to improve reusability and error handling
  src/Nav/index.tsx
  src/Nav/stories/Nav.WithLogo.stories.tsx
  src/Nav/stories/Nav.stories.tsx
  src/Nav/styles.js
  src/NavLink/index.tsx
  src/NavLink/styles.js
  src/index.ts
Labels: major

#59 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#60 Update icon dependency to latest version
  package.json
Labels: minor, dependencies

#62 fix: add scroll-y behavior of nav
  src/Nav/stories/Nav.WithLogo.stories.tsx
  src/Nav/stories/Nav.stories.tsx
  src/Nav/styles.js
Labels: patch
